emotion_mapping_table = {
    "Admiration": "감탄",
    "Adoration": "흠모",
    "Aesthetic Appreciation": "미적 감상",
    "Amusement": "재미",
    "Anger": "분노",
    "Annoyance": "짜증",
    "Anxiety": "불안",
    "Awe": "경외감",
    "Awkwardness": "어색함",
    "Boredom": "지루함",
    "Calmness": "평온",
    "Concentration": "집중",
    "Confusion": "혼란",
    "Contemplation": "숙고",
    "Contempt": "경멸",
    "Contentment": "만족감",
    "Craving": "갈망",
    "Desire": "욕망",
    "Determination": "결단력",
    "Disappointment": "실망",
    "Disapproval": "불찬성",
    "Disgust": "혐오감",
    "Distress": "고통",
    "Doubt": "의심",
    "Ecstasy": "황홀감",
    "Embarrassment": "당혹감",
    "Empathic Pain": "공감의 고통",
    "Enthusiasm": "열정",
    "Entrancement": "넋을 잃음",
    "Envy": "질투",
    "Excitement": "흥분",
    "Fear": "두려움",
    "Gratitude": "감사",
    "Guilt": "죄책감",
    "Horror": "공포",
    "Interest": "흥미",
    "Joy": "기쁨",
    "Love": "사랑",
    "Nostalgia": "향수",
    "Pain": "고통",
    "Pride": "자부심",
    "Realization": "깨달음",
    "Relief": "안도감",
    "Romance": "낭만",
    "Sadness": "슬픔",
    "Sarcasm": "빈정거림",
    "Satisfaction": "만족",
    "Shame": "수치심",
    "Surprise (negative)": "부정적 놀람",
    "Surprise (positive)": "긍정적 놀람",
    "Sympathy": "동정",
    "Tiredness": "피로",
    "Triumph": "승리감"
}

def map_emotion(emotion: str) -> str :
    return emotion_mapping_table.get(emotion, None)